/*
================================================================================
  미래가치쿼리 리팩토링
  [주요 변경]
  1. DATABIZ_FUTVAL_STF_CHNL_MAP 신규: CHNL CASE WHEN 55줄 → 2개 테이블 공유
  2. ALL_CR_TEMP_PRED에 GD_TYPE 추가 (GDREC_TMGD_LIST JOIN) → PL/CR_GD/LA_PRM CASE WHEN 제거
  3. CUS_INFO 테이블: F_BIRTH_DAY_DEC/F_SEX_DEC 서브쿼리로 1회 호출
  4. SPJOB_YN: LIKE 30개 → REGEXP_LIKE
  5. CLM_PRED: UNION → UNION ALL (소스 테이블 완전 다름, 중복 불가)
  6. SEG_MKTG_PRES_CVR_INFO: UNION ALL 17개 → UNPIVOT
  7. ON 0=0 패턴 제거, DISTINCT → GROUP BY
================================================================================
*/


/* ============================================================================
   [헬퍼] 채널 분류 매핑 — ALL_CR_TEMP + CRM_MART_ALL_CR_TEMP 공유
   원본 55줄 CASE WHEN을 1회만 정의
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_STF_CHNL_MAP PURGE;
CREATE TABLE DATABIZ_FUTVAL_STF_CHNL_MAP AS
SELECT
    CLS_YYMM, STFNO,
    CASE
        WHEN STFNO = '8901911'                                            THEN '61'
        WHEN STFNO = '6009607'                                            THEN '11'
        WHEN BZ_ATRCD IN ('30','31')                                      THEN '62'
        WHEN BRNM LIKE '%LIFE%'                                           THEN '62'
        WHEN TMNM LIKE '%교차%'                                            THEN '12'
        WHEN BR_ORGCD IN ('1301406','1301908','1302142')                   THEN '12'
        WHEN TMNM LIKE '%한생GA팀%'                                        THEN '20'
        WHEN BZ_FML_QUFCD IN ('G01')                                      THEN '20'
        WHEN BZ_ATRCD IN ('15','16','18','97','27')                       THEN '12'
        WHEN BZ_FML_QUFCD IN ('39','47','56')                             THEN '12'
        WHEN BZ_PART_FLGCD = '06'
             AND COALESCE(BZ_ATRCD,'00') NOT IN ('15','16','18','97','27')
             AND BRNM NOT LIKE '%TM%'                                     THEN '11'
        WHEN BZ_PART_FLGCD = '06'
             AND BZ_FML_QUFCD IS NULL
             AND BRNM NOT LIKE '%TM%'                                     THEN '11'
        WHEN BRNM LIKE '%지역단%'                                          THEN '11'
        WHEN BRNM LIKE '%GA사업단%' OR BRNM LIKE '%HF%'                   THEN '20'
        WHEN HDQT_ORGCD IN ('1300011','1302011','1303011')
          OR (HDQT_ORGCD='1301318' AND BR_ORGCD='1301321')
          OR (HDQT_ORGCD='1300007' AND BR_ORGCD='1301040')
          OR (HDQT_ORGCD='1300008' AND BR_ORGCD='1301322')
          OR  BR_ORGCD = '1301409'
          OR (BR_ORGCD = '1300163' AND BZP_ORGCD='1301383')
          OR (BR_ORGCD = '1301040' AND BZP_ORGCD='1301396')
          OR (BR_ORGCD = '1300090' AND BZP_ORGCD='1301384')              THEN '20'
        WHEN STFNO = '8066063' AND BZP_ORGCD = '1301581'                 THEN '31'
        WHEN STFNO IN ('8066063','8066059','6010186','3449868')           THEN '32'
        WHEN HDQT_ORGCD IN ('1300013','1300287','1300288')                THEN '40'
        WHEN HDQT_ORGCD IN ('1300012','1301363','1303053')                THEN '31'
        WHEN BR_ORGCD   IN ('1300280','1301363','1303054','1303055')      THEN '31'
        WHEN BR_ORGCD   IN ('1300287','1201452')                          THEN '40'
        WHEN HDQT_ORGCD IN ('1301776','1301362','1301828')                THEN '50'
        WHEN BZ_PART_FLGNM = '법인영업' AND BZP_NM NOT LIKE '%신채널%'    THEN '50'
        WHEN BZP_ORGCD IN (
              '1301364','1301365','1301366','1301367','1301368','1301369',
              '1301370','1301371','1301372','1301373','1301618','1301750',
              '1301751','1301752','1301753','1301754','1301755','1301756',
              '1301757','1301758','1301786','1301968','1302015','1302016') THEN '50'
        WHEN BZP_NM  LIKE '%기업영업%' OR BZP_NM  LIKE '%법인영업%'
          OR BRNM    LIKE '%기업영업%' OR BRNM    LIKE '%법인영업%'
          OR HDQNM   LIKE '%기업영업%' OR HDQNM   LIKE '%법인영업%'
          OR BRNM    LIKE '%전략영업%' OR BRNM    LIKE '%GA영업%'         THEN '50'
        WHEN BZ_PART_FLGNM = '본사/기타' AND BRNM NOT LIKE '%TM%'        THEN '61'
        ELSE '61'
    END AS CHNL
FROM M_ORG_MTHY_BZ_ORGN;


/* ============================================================================
   [1] 전체 계약 + 채널 + GD_TYPE
   ※ CHNL: DATABIZ_FUTVAL_STF_CHNL_MAP 재사용 (이전월 org 기준)
   ※ GD_TYPE: GDREC_TMGD_LIST JOIN → 하위 PL_PRED/CR_GD_PRED CASE WHEN 제거
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_ALL_CR_TEMP_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_ALL_CR_TEMP_PRED AS
SELECT A.*, B.CHNL, G.GD_TYPE
FROM DATABIZ_FUTVAL_YYMM_PRED T
LEFT JOIN M_CRM_MTHY_PS_CR A
    ON A.CLS_YYMM = T.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_STF_CHNL_MAP B
    ON F_PREV_MONTH(T.CLS_YYMM,'-1') = B.CLS_YYMM
    AND A.DH_STFNO = B.STFNO
LEFT JOIN GDREC_TMGD_LIST G
    ON A.GDCD = G.GDCD;


/* ============================================================================
   [2] 고객 기본정보 (계약자/피보험자 연령·성별·보험종류)
   ※ F_BIRTH_DAY_DEC/F_SEX_DEC: 서브쿼리에서 1회 호출 후 GROUP BY에서 재사용
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_ALL_CUS_INFO_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_ALL_CUS_INFO_PRED AS
SELECT
    CLS_YYMM, CTMNO, DH_STFNO, RELPC_TPCD
    , CASE WHEN F_ISDATE(BRTH) = 'T'
           THEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(CLS_YYMM), TO_DATE(BRTH,'YYYYMMDD')) / 12)
      END AS CTM_AGE
    , CASE WHEN SEX = 'M' THEN '1.M' WHEN SEX = 'F' THEN '2.F' END AS CTM_SEX
    , MAX(CASE WHEN IKD_GRPCD = 'LA'       THEN 1 ELSE 0 END) AS LA_YN
    , MAX(CASE WHEN IKD_GRPCD = 'CA'       THEN 1 ELSE 0 END) AS CA_YN
    , MAX(CASE WHEN IKD_GRPCD IN ('FA','MA') THEN 1 ELSE 0 END) AS FAMA_YN
FROM (
    SELECT A.CLS_YYMM, A.DH_STFNO,
           C.CTMNO, C.RELPC_TPCD, C.IKD_GRPCD,
           F_BIRTH_DAY_DEC(C.CTM_DSCNO) AS BRTH,
           F_SEX_DEC(C.CTM_DSCNO)       AS SEX
    FROM DATABIZ_FUTVAL_ALL_CR_TEMP_PRED A
    INNER JOIN DATABIZ_FUTVAL_YYMM_PRED T ON A.CLS_YYMM = T.CLS_YYMM
    INNER JOIN INS_CR_RELPC C
        ON A.PLYNO = C.PLYNO
        AND C.NDS_AP_STR_DTHMS <= T.CLS_NDDT
        AND C.NDS_AP_ND_DTHMS   > T.CLS_NDDT
        AND C.RELPC_TPCD IN ('01','02')
        AND C.RELPC_STCD IN ('01','04')
)
GROUP BY CLS_YYMM, CTMNO, DH_STFNO, RELPC_TPCD, BRTH, SEX;


/* ============================================================================
   [3] 직업 분류
   ※ SPJOB_YN: LIKE 30개 → REGEXP_LIKE 2개 (포함/제외)
   ※ ON 0=0 → 직접 JOIN 조건
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CUS_JOB_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CUS_JOB_PRED AS
SELECT
    A.*
    , CASE WHEN SPJOB_YN = 1             THEN '전문직'
           WHEN STF_YN  = '내근직'       THEN '내근직'
           WHEN STF_YN  = '영업가족'     THEN '영업가족'
           WHEN JB_TYPE IN ('1','2','3') THEN '화이트'
           WHEN JB_TYPE IN ('4','5')     THEN '자영업'
           WHEN JB_TYPE IN ('B1','C','B2') THEN '주부/학생'
           ELSE '블루' END AS JB_SEG
FROM (
    SELECT A.*
        , E2.JBNM, E3.BZPS_TPCD
        , CASE
            WHEN REGEXP_LIKE(E2.JBNM,
                 '전문 간호|조종사|관제사|항해사|선박 기관사|선장|교수|고위|임원|경무관 이상|'||
                 '소방감 이상|계리|금융 상품|자산|외환 딜러|소프트웨어|프로그래머|데이터|'||
                 '감독|장학관|판사|검사|변호사|법무사|변리사|노무사|회계사|세무사|'||
                 '감정평가사|관세사|의사|치과의사|수의사|한의사|약사|손해사정사|건축사|행정사|도선사')
             AND NOT REGEXP_LIKE(E2.JBNM,
                 '장의사|스포츠|건설|코치|검사원|검사공|검사기사|사육|판매|사무원|'||
                 '종사원|의료인|공무원|보조원|현장기술|감독자|제조|공급|사무및감독|경비원')
            THEN 1 ELSE 0 END AS SPJOB_YN
        , CASE WHEN E4.BZ_PART_FLGCD = '09' AND E4.STF_BZ_STCD = '01' THEN '내근직'
               WHEN E4.STFNO IS NOT NULL     AND E4.STF_BZ_STCD = '01' THEN '영업가족'
          END AS STF_YN
        , CASE WHEN E2.JBNM LIKE '%주부%'                            THEN 'B2'
               WHEN E1.JBCD='0' AND E1.JB_CH_SEQNO='2'             THEN '1'
               WHEN E1.JBCD='1' AND E1.JB_CH_SEQNO='2'             THEN '2'
               WHEN E1.JBCD='1' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '1'
               WHEN E1.JBCD='2' AND E1.JB_CH_SEQNO IN ('2','3','4') THEN '2'
               WHEN E1.JBCD='3' AND E1.JB_CH_SEQNO='2'             THEN '2'
               WHEN E1.JBCD='3' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '3'
               WHEN E1.JBCD='4' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '4'
               WHEN E1.JBCD='5' AND E1.JB_CH_SEQNO='2'             THEN '4'
               WHEN E1.JBCD IN ('6','8','9') AND E1.JB_CH_SEQNO='1' THEN '4'
               WHEN E1.JBCD='4' AND E1.JB_CH_SEQNO='2'             THEN '5'
               WHEN E1.JBCD='5' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '5'
               WHEN E1.JBCD='1' AND E1.JB_CH_SEQNO='1'             THEN '6'
               WHEN E1.JBCD='6' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '6'
               WHEN E1.JBCD='9' AND E1.JB_CH_SEQNO='2'             THEN '6'
               WHEN E1.JBCD='4' AND E1.JB_CH_SEQNO='1'             THEN '7'
               WHEN E1.JBCD='5' AND E1.JB_CH_SEQNO='1'             THEN '7'
               WHEN E1.JBCD IN ('6','7','8') AND E1.JB_CH_SEQNO='2' THEN '7'
               WHEN E1.JBCD='7' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '7'
               WHEN E1.JBCD IN ('3','7') AND E1.JB_CH_SEQNO='1'    THEN '8'
               WHEN E1.JBCD='8' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '8'
               WHEN E1.JBCD='2' AND E1.JB_CH_SEQNO='1'             THEN '9'
               WHEN E1.JBCD='9' AND E1.JB_CH_SEQNO IN ('3','4')    THEN '9'
               WHEN E1.JBCD='A' AND E1.JB_CH_SEQNO IN ('2','3','4') THEN 'A'
               WHEN E1.JBCD='B' AND E1.JB_CH_SEQNO IN ('2','3','4') THEN 'B1'
               WHEN E2.JBCD='B3200'                                  THEN 'B2'
               ELSE 'C'
          END AS JB_TYPE
    FROM (
        SELECT AA.CLS_YYMM, AA.CTMNO, BB.JBCD, BB.JB_CH_SEQNO
            , ROW_NUMBER() OVER (PARTITION BY AA.CLS_YYMM, AA.CTMNO
                                 ORDER BY BB.AP_STR_DTHMS DESC) AS RN
        FROM SDADAM.DATABIZ_FUTVAL_ALL_CUS_INFO_PRED AA
        LEFT JOIN CUS_CTM_JB_CRR BB
            ON AA.CTMNO = BB.CTMNO
            AND BB.AP_STR_DTHMS <= F_LAST_DAY(AA.CLS_YYMM)
            AND BB.AP_ND_DTHMS   > F_LAST_DAY(AA.CLS_YYMM)
    ) A
    LEFT JOIN CUS_JB   E1 ON SUBSTR(A.JBCD,1,1) = E1.JBCD AND A.JB_CH_SEQNO = E1.JB_CH_SEQNO
    LEFT JOIN CUS_JB   E2 ON A.JBCD = E2.JBCD AND A.JB_CH_SEQNO = E2.JB_CH_SEQNO
    LEFT JOIN CUS_CTM  E3 ON A.CTMNO = E3.CTMNO
    LEFT JOIN M_ORG_BZ_ORGN E4 ON E3.CTM_DSCNO = E4.RSNO AND E4.STF_BZ_STCD = '01'
    WHERE A.RN = 1
) A;


/* ============================================================================
   [4] 고객 주소 + 직업코드
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CUS_ADD_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CUS_ADD_PRED AS
SELECT
    A1.CLS_YYMM, A1.CTMNO, CTM_SEX
    , CASE WHEN CTM_AGE BETWEEN 18 AND 29 THEN '20대 이하'
           WHEN CTM_AGE BETWEEN 30 AND 39 THEN '30대'
           WHEN CTM_AGE BETWEEN 40 AND 49 THEN '40대'
           WHEN CTM_AGE BETWEEN 50 AND 59 THEN '50대'
           WHEN CTM_AGE BETWEEN 60 AND 99 THEN '60대 이상'
           ELSE NULL END AS AGE_CD
    , CTM_AGE, SD, SGNG, PSTNO, PSTNO_ID
    , E.JBCD, E.JB_CH_SEQNO, F.JBNM
FROM (
    SELECT DISTINCT
        T.CLS_YYMM, T.CTMNO, T.CTM_SEX, T.CTM_AGE
        , A.SD, A.SGNG, A.PSTNO
        , COALESCE(B.PSTNO_ID, C.PSTNO_ID, D.PSTNO_ID) AS PSTNO_ID
        , ROW_NUMBER() OVER (
            PARTITION BY T.CLS_YYMM, T.CTMNO
            ORDER BY A.AP_STR_DTHMS DESC,
                     CASE WHEN B.PSTNO_ID IS NULL THEN 1 ELSE 0 END,
                     CASE WHEN C.PSTNO_ID IS NULL THEN 1 ELSE 0 END
          ) AS RK
    FROM DATABIZ_FUTVAL_ALL_CUS_INFO_PRED T
    INNER JOIN CUS_CTM_ADR_CRR A
        ON T.CTMNO = A.CTMNO
        AND A.AP_ND_DTHMS  >= F_LAST_DAY(T.CLS_YYMM)
        AND A.AP_STR_DTHMS  < F_LAST_DAY(T.CLS_YYMM)
        AND A.ADR_FLGCD = '100'
    LEFT JOIN CUS_PSTNO_RODNM_BA_ADR B ON A.BLD_ADMNO = B.BLD_ADMNO
    LEFT JOIN CUS_PSTNO_RODNM_BA_ADR C
        ON A.PSTNO = C.PSTNO AND A.SD = C.SD AND A.SGNG = C.SGNG
        AND A.ROAD_NM = C.ROAD_NM AND A.MN_BLDNO = C.MN_BLDNO
        AND COALESCE(A.SUB_BLDNO,'0') = COALESCE(C.SUB_BLDNO,'0')
    LEFT JOIN CUS_PSTNO_RODNM_BA_ADR D
        ON A.PSTNO = D.PSTNO AND A.SD = D.SD AND A.SGNG = D.SGNG
        AND A.ROAD_NM = D.ROAD_NM AND A.MN_BLDNO = D.MN_BLDNO
) A1
LEFT JOIN CUS_CTM_JB_CRR E
    ON A1.CTMNO = E.CTMNO
    AND E.AP_STR_DTHMS <= F_LAST_DAY(A1.CLS_YYMM)
    AND E.AP_ND_DTHMS   > F_LAST_DAY(A1.CLS_YYMM)
LEFT JOIN CUS_JB F
    ON E.JBCD = F.JBCD AND E.JB_CH_SEQNO = F.JB_CH_SEQNO
WHERE RK = 1;


/* ============================================================================
   [5] 소득/신용 추가
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CUS_ADD_INCOME_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CUS_ADD_INCOME_PRED AS
SELECT DISTINCT
    CLS_YYMM, CTMNO, CTM_SEX, AGE_CD, CTM_AGE
    , SD, SGNG, PSTNO, PSTNO_ID, JBCD, JB_CH_SEQNO, JBNM
    , NVL(INCOME_SEG, INCOME) AS INCOME
    , NVL(CREDIT_SEG, CREDIT) AS CREDIT
FROM (
    SELECT B.*
        , CASE WHEN H.전문직=1 THEN COALESCE(D.SPJOB_AVG_ICAMT,D1.SPJOB_AVG_ICAMT,F.SPJOB_AVG_ICAMT,F1.SPJOB_AVG_ICAMT,D2.SPJOB_AVG_ICAMT,D3.SPJOB_AVG_ICAMT,F2.SPJOB_AVG_ICAMT,F3.SPJOB_AVG_ICAMT)
               WHEN H.법인대표=1 THEN COALESCE(D.CRP_PRS_AVG_ICAMT,D1.CRP_PRS_AVG_ICAMT,F.CRP_PRS_AVG_ICAMT,F1.CRP_PRS_AVG_ICAMT,D2.CRP_PRS_AVG_ICAMT,D3.CRP_PRS_AVG_ICAMT,F2.CRP_PRS_AVG_ICAMT,F3.CRP_PRS_AVG_ICAMT)
               WHEN H.자영업=1  THEN COALESCE(D.SFEMP_AVG_ICAMT,D1.SFEMP_AVG_ICAMT,F.SFEMP_AVG_ICAMT,F1.SFEMP_AVG_ICAMT,D2.SFEMP_AVG_ICAMT,D3.SFEMP_AVG_ICAMT,F2.SFEMP_AVG_ICAMT,F3.SFEMP_AVG_ICAMT)
               WHEN H.주부!=1 AND H.학생!=1 AND H.무직!=1
                   THEN COALESCE(D.LBR_ICR_AVG_ICAMT,D1.LBR_ICR_AVG_ICAMT,F.LBR_ICR_AVG_ICAMT,F1.LBR_ICR_AVG_ICAMT,D2.LBR_ICR_AVG_ICAMT,D3.LBR_ICR_AVG_ICAMT,F2.LBR_ICR_AVG_ICAMT,F3.LBR_ICR_AVG_ICAMT)
               ELSE NULL END AS INCOME_SEG
        , COALESCE(D.AVG_ICAMT,D1.AVG_ICAMT,F.AVG_ICAMT,F1.AVG_ICAMT,D2.AVG_ICAMT,D3.AVG_ICAMT,F2.AVG_ICAMT,F3.AVG_ICAMT) AS INCOME
        , CASE WHEN H.주부=1   THEN COALESCE(D.HMKR_CRDVL_AVG_POCT,D1.HMKR_CRDVL_AVG_POCT,F.HMKR_CRDVL_AVG_POCT,F1.HMKR_CRDVL_AVG_POCT,D2.HMKR_CRDVL_AVG_POCT,D3.HMKR_CRDVL_AVG_POCT,F2.HMKR_CRDVL_AVG_POCT,F3.HMKR_CRDVL_AVG_POCT)
               WHEN H.학생=1   THEN COALESCE(D.STT_CRDVL_AVG_POCT,D1.STT_CRDVL_AVG_POCT,F.STT_CRDVL_AVG_POCT,F1.STT_CRDVL_AVG_POCT,D2.STT_CRDVL_AVG_POCT,D3.STT_CRDVL_AVG_POCT,F2.STT_CRDVL_AVG_POCT,F3.STT_CRDVL_AVG_POCT)
               WHEN H.무직=1   THEN COALESCE(D.OTJOB_CRDVL_AVG_POCT,D1.OTJOB_CRDVL_AVG_POCT,F.OTJOB_CRDVL_AVG_POCT,F1.OTJOB_CRDVL_AVG_POCT,D2.OTJOB_CRDVL_AVG_POCT,D3.OTJOB_CRDVL_AVG_POCT,F2.OTJOB_CRDVL_AVG_POCT,F3.OTJOB_CRDVL_AVG_POCT)
               WHEN H.전문직=1 THEN COALESCE(D.SPJOB_CRDVL_AVG_POCT,D1.SPJOB_CRDVL_AVG_POCT,F.SPJOB_CRDVL_AVG_POCT,F1.SPJOB_CRDVL_AVG_POCT,D2.SPJOB_CRDVL_AVG_POCT,D3.SPJOB_CRDVL_AVG_POCT,F2.SPJOB_CRDVL_AVG_POCT,F3.SPJOB_CRDVL_AVG_POCT)
               WHEN H.법인대표=1 THEN COALESCE(D.CRP_PRS_CRDVL_AVG_POCT,D1.CRP_PRS_CRDVL_AVG_POCT,F.CRP_PRS_CRDVL_AVG_POCT,F1.CRP_PRS_CRDVL_AVG_POCT,D2.CRP_PRS_CRDVL_AVG_POCT,D3.CRP_PRS_CRDVL_AVG_POCT,F2.CRP_PRS_CRDVL_AVG_POCT,F3.CRP_PRS_CRDVL_AVG_POCT)
               WHEN H.자영업=1  THEN COALESCE(D.SFEMP_CRDVL_AVG_POCT,D1.SFEMP_CRDVL_AVG_POCT,F.SFEMP_CRDVL_AVG_POCT,F1.SFEMP_CRDVL_AVG_POCT,D2.SFEMP_CRDVL_AVG_POCT,D3.SFEMP_CRDVL_AVG_POCT,F2.SFEMP_CRDVL_AVG_POCT,F3.SFEMP_CRDVL_AVG_POCT)
               ELSE NULL END AS CREDIT_SEG
        , COALESCE(D.AVG_CRD_VLPOC,D1.AVG_CRD_VLPOC,F.AVG_CRD_VLPOC,F1.AVG_CRD_VLPOC,D2.AVG_CRD_VLPOC,D3.AVG_CRD_VLPOC,F2.AVG_CRD_VLPOC,F3.AVG_CRD_VLPOC) AS CREDIT
    FROM SDADAM.DATABIZ_FUTVAL_CUS_ADD_PRED B
    LEFT JOIN CUS_PSTNO_BAADR_SCT_ID C ON B.PSTNO_ID = C.PSTNO_ID
    LEFT JOIN M_CRM_IC_CRD_GRID_ST_STS D  ON C.BAADR_SCT_ID=D.TOT_UNT_GRID_NM AND B.CTM_SEX=D.SEXCD AND B.AGE_CD=D.AGGB_NM AND D.ST_YYMM='202312'
    LEFT JOIN M_CRM_IC_CRD_GRID_ST_STS D1 ON C.BAADR_SCT_ID=D1.TOT_UNT_GRID_NM AND D1.SEXCD='ALL' AND B.AGE_CD=D1.AGGB_NM AND D1.ST_YYMM='202312'
    LEFT JOIN M_CRM_IC_CRD_GRID_ST_STS D2 ON C.BAADR_SCT_ID=D2.TOT_UNT_GRID_NM AND B.CTM_SEX=D2.SEXCD AND D2.AGGB_NM='ALL' AND D2.ST_YYMM='202312'
    LEFT JOIN M_CRM_IC_CRD_GRID_ST_STS D3 ON C.BAADR_SCT_ID=D3.TOT_UNT_GRID_NM AND D3.SEXCD='ALL' AND D3.AGGB_NM='ALL' AND D3.ST_YYMM='202312'
    LEFT JOIN M_CRM_IC_CRD_PSTNO_ST_STS F  ON B.PSTNO=F.TOT_UNT_PSTNO AND B.CTM_SEX=F.SEXCD AND B.AGE_CD=F.AGGB_NM AND F.ST_YYMM='202312'
    LEFT JOIN M_CRM_IC_CRD_PSTNO_ST_STS F1 ON B.PSTNO=F1.TOT_UNT_PSTNO AND F1.SEXCD='ALL' AND B.AGE_CD=F1.AGGB_NM AND F1.ST_YYMM='202312'
    LEFT JOIN M_CRM_IC_CRD_PSTNO_ST_STS F2 ON B.PSTNO=F2.TOT_UNT_PSTNO AND B.CTM_SEX=F2.SEXCD AND F2.AGGB_NM='ALL' AND F2.ST_YYMM='202312'
    LEFT JOIN M_CRM_IC_CRD_PSTNO_ST_STS F3 ON B.PSTNO=F3.TOT_UNT_PSTNO AND F3.SEXCD='ALL' AND F3.AGGB_NM='ALL' AND F3.ST_YYMM='202312'
    LEFT JOIN (
        SELECT
            CASE WHEN (REGEXP_LIKE(A.JBNM,'판사|검사|변호사|법무사|변리사|노무사|회계사|세무사|감정평가사|관세사|의사|치과의사|수의사|한의사|약사|행정사|손해사정사|건축사|도선사|조종사|계리|교수|관제사')
                       OR REGEXP_LIKE(A.JBNM,'전문 간호|항해사|선박 기관사|선장|고위|임원|경무관 이상|소방감 이상|금융 상품|자산|외환 딜러|소프트웨어|프로그래머|데이터|감독|장학관'))
                 AND NOT REGEXP_LIKE(A.JBNM,'장의사|스포츠|건설|코치|검사원|검사공|검사기사|사육|판매|사무원|종사원|의료인|공무원|보조원|현장기술|감독자|제조|공급|사무및감독|경비원')
                 THEN 1 ELSE 0 END AS 전문직
            , CASE WHEN (JBNM LIKE '%대표%' AND JBCD LIKE '1%') OR JBNM LIKE '%임원%'
                        OR JBNM LIKE '%경영 및 진단 전문가%' OR JBNM LIKE '%경영인%'
                        OR JBNM LIKE '%경영부서관리자%' THEN 1 ELSE 0 END AS 법인대표
            , CASE WHEN JBNM LIKE '%자영업자%' OR JBNM LIKE '%경영자%'
                     OR (JBNM LIKE '%운영%' AND JBNM NOT LIKE '%시스템%' AND JBNM NOT LIKE '%전산%'
                         AND JBNM NOT LIKE '%정보%' AND JBNM NOT LIKE '%기술%'
                         AND JBNM NOT LIKE '%연구%' AND JBNM NOT LIKE '%사무%')
                     OR JBNM LIKE '%소매%' OR (JBNM LIKE '%음식%' AND JBNM LIKE '%서비스%')
                     OR (JBNM LIKE '%조리%' AND JBNM NOT LIKE '%산후%' AND JBNM NOT LIKE '%열차%'
                         AND JBNM NOT LIKE '%선박%' AND JBNM NOT LIKE '%호텔%' AND JBNM NOT LIKE '%병원%')
                     OR JBNM LIKE '%피부%' OR JBNM LIKE '%커피%' OR JBNM LIKE '%식당 종사원%'
                     OR JBNM LIKE '%주방장%' OR JBNM LIKE '%미용사%' OR JBNM LIKE '%매장 계산원%'
                     OR JBNM LIKE '%음료서비스원%' OR JBNM LIKE '%노래방%'
                     OR JBNM LIKE '%자동차 경정비원%' OR JBNM LIKE '%부동산 컨설턴트%'
                     THEN 1 ELSE 0 END AS 자영업
            , CASE WHEN JBNM LIKE '%주부%' THEN 1 ELSE 0 END AS 주부
            , CASE WHEN JBNM LIKE '%학생%' THEN 1 ELSE 0 END AS 학생
            , CASE WHEN JBNM LIKE '%무직%' AND JBNM NOT LIKE '%사무직%' THEN 1 ELSE 0 END AS 무직
            , A.*
        FROM CUS_JB A WHERE LENGTH(JBCD) > 4
    ) H ON H.JBCD = B.JBCD AND H.JB_CH_SEQNO = B.JB_CH_SEQNO
);


/* ============================================================================
   [6] 고객 마케팅 정보
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CUS_INFO_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CUS_INFO_PRED AS
SELECT
    A.*
    , MONTHS_BETWEEN(F_LAST_DAY(B.CLS_YYMM), HOME_ADR_CHDT)           AS HOME_ADR_CHDT
    , MONTHS_BETWEEN(F_LAST_DAY(B.CLS_YYMM), LATS_CR_CC_AGMDT)        AS LATS_CR_CC_AGMDT
    , MONTHS_BETWEEN(F_LAST_DAY(B.CLS_YYMM), MKTG_COLUS_UTAGR_STRDT)  AS MKTG_COLUS_UTAGR_STRDT
    , MONTHS_BETWEEN(F_LAST_DAY(B.CLS_YYMM), MKTG_THRPS_UTAGR_STRDT)  AS MKTG_THRPS_UTAGR_STRDT
    , MONTHS_BETWEEN(F_LAST_DAY(B.CLS_YYMM), LATS_CRNTC_MAIL_RCVDT)   AS LATS_CRNTC_MAIL_RCVDT
FROM DATABIZ_FUTVAL_ALL_CUS_INFO_PRED A
LEFT JOIN M_CRM_MTHY_PSN_CTM_INFO B
    ON A.CTMNO = B.CTMNO AND A.CLS_YYMM = B.CLS_YYMM;


/* ============================================================================
   [7] 채널별 계약수 PIVOT
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CR_CHNL_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CR_CHNL_PRED AS
SELECT *
FROM (
    SELECT A.CLS_YYMM, C.CTMNO, A.CHNL
        , COUNT(DISTINCT A.PLYNO) AS PLYNO_CNT
    FROM DATABIZ_FUTVAL_ALL_CR_TEMP_PRED A
    INNER JOIN INS_CR_RELPC C
        ON A.PLYNO = C.PLYNO
        AND C.NDS_AP_STR_DTHMS <= F_LAST_DAY(A.CLS_YYMM)
        AND C.NDS_AP_ND_DTHMS   > F_LAST_DAY(A.CLS_YYMM)
        AND C.RELPC_TPCD IN ('02')
        AND C.RELPC_STCD IN ('01','04')
        AND C.RELPC_DSCNO_FLGCD IN ('01','05')
    WHERE A.IKD_GRPCD = 'LA'
    GROUP BY A.CLS_YYMM, C.CTMNO, A.CHNL
)
PIVOT (MAX(PLYNO_CNT) FOR CHNL IN (
    '11' AS 전속,'12' AS 교차,'20' AS GA,'31' AS TM,
    '32' AS CM,'40' AS 방카,'50' AS 기업,'61' AS LIFEWITH,'62' AS 본사기타
)) P;


/* ============================================================================
   [8] 계약 이력 (최초가입일, 해지계약수)
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CR_CRR_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CR_CRR_PRED AS
SELECT CLS_YYMM, CTMNO, DH_STFNO
    , MAX(INS_ST) AS MX_INS
    , COUNT(DISTINCT CASE WHEN CR_STCD NOT IN ('00','12') THEN PLYNO END) AS CCL_CR_CNT
FROM (
    SELECT T.CLS_YYMM, C.CTMNO, A.PLYNO, A.INS_ST, D1.DH_STFNO, B.CR_STCD
    FROM DATABIZ_FUTVAL_YYMM_PRED T
    INNER JOIN INS_INS_CR A
        ON A.AP_STRDT  <= T.CLS_NDDT_TS AND A.AP_NDDT    > T.CLS_NDDT_TS
        AND A.INS_CLSTR > T.CLS_NDDT_TS AND A.INS_ST    <= T.CLS_NDDT_TS
        AND A.IKD_GRPCD = 'LA'
    INNER JOIN INS_CR_ST_CRR B
        ON A.PLYNO = B.PLYNO
        AND B.NDS_AP_STR_DTHMS <= T.CLS_NDDT_TS AND B.NDS_AP_ND_DTHMS > T.CLS_NDDT_TS
    INNER JOIN INS_CR_RELPC C
        ON A.PLYNO = C.PLYNO
        AND C.NDS_AP_STR_DTHMS <= T.CLS_NDDT_TS AND C.NDS_AP_ND_DTHMS > T.CLS_NDDT_TS
        AND C.RELPC_TPCD IN ('02')
        AND C.RELPC_STCD IN ('01','04')
        AND C.RELPC_DSCNO_FLGCD IN ('01','05')
    LEFT JOIN INS_CR_DH_STF_CRR D1
        ON A.PLYNO = D1.PLYNO
        AND D1.NDS_AP_STR_DTHMS <= T.CLS_NDDT_TS AND D1.NDS_AP_ND_DTHMS > T.CLS_NDDT_TS
        AND D1.DH_STF_TPCD = '01' AND D1.PRS_DH_STF_YN = '1'
    WHERE EXISTS (SELECT 1 FROM DATABIZ_FUTVAL_ALL_CUS_INFO_PRED D WHERE D.CTMNO = C.CTMNO)
)
GROUP BY CLS_YYMM, CTMNO, DH_STFNO;


/* ============================================================================
   [9] 설계이력
   ※ GD_TYPE: M_CRM_GD_CSF_INFO + CASE WHEN → GDREC_TMGD_LIST JOIN으로 대체
   ※ WHERE IN (SELECT DISTINCT ...) → EXISTS로 (semi-join, DISTINCT 스캔 방지)
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_PL_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_PL_PRED AS
SELECT *
FROM (
    SELECT DISTINCT
        AA.CLS_YYMM, AA.PLNO, AA.PLDT, AA.PL_STCD, AA.PL_ST_CHDT
        , AA.DH_STFNO AS CE_STFNO, AA.USRNO AS CE_USRNO
        , BB.CTMNO, BB.RELPC_TPCD
        , AA.PLNM, AA.GD_TYPE, AA.PL_FIN_CD
        , ROW_NUMBER() OVER (PARTITION BY AA.CLS_YYMM, AA.PLNO ORDER BY AA.PLDT DESC) AS RN
    FROM (
        SELECT
            T.CLS_YYMM, A.PLNO, A.PLDT, A.CGAF_CH_SEQNO
            , A.PL_STCD, A.PL_ST_CHDT, B.DH_STFNO, B.USRNO, C.PLNM
            , G.GD_TYPE
            , CASE WHEN A.PL_STCD IN ('03','04','05','06','07','08','09') THEN 1 ELSE 0 END AS PL_FIN_CD
        FROM DATABIZ_FUTVAL_YYMM_PRED T
        INNER JOIN INS_INS_PL A ON A.PLDT <= FIRST_DAY(T.CLS_YYMM)
        LEFT JOIN INS_PL_DH_STF B
            ON A.PLNO = B.PLNO AND A.CGAF_CH_SEQNO = B.CGAF_CH_SEQNO
            AND B.DH_STF_TPCD = '01' AND B.IKD_GRPCD = 'LA'
        LEFT JOIN INS_GD_CE_PL C ON A.PLCD = C.PLCD AND A.GDCD = C.GDCD
        LEFT JOIN GDREC_TMGD_LIST G ON A.GDCD = G.GDCD
        WHERE A.PL_FLGCD = '01' AND A.IKD_GRPCD = 'LA' AND A.VALD_PL_YN = '1'
    ) AA
    INNER JOIN INS_PL_RELPC BB
        ON AA.PLNO = BB.PLNO AND AA.CGAF_CH_SEQNO = BB.CGAF_CH_SEQNO
        AND BB.IKD_GRPCD = 'LA' AND BB.RELPC_TPCD IN ('01','02')
    WHERE EXISTS (SELECT 1 FROM DATABIZ_FUTVAL_ALL_CUS_INFO_PRED X WHERE X.CTMNO = BB.CTMNO)
)
WHERE RN = 1;


/* ============================================================================
   [10] 사고/지급보험금
   ※ UNION → UNION ALL: 장기(M_CMP_GN_CVRCL_PY_IBNF_LIST)와 자동차(M_CMP_CR_CLM_CRST)는
      완전히 다른 소스 → 중복 불가, UNION의 DISTINCT 연산 불필요
   ※ DISTINCT → GROUP BY 집계
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CLM_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CLM_PRED AS
-- 장기 보험
SELECT T.CLS_YYMM, T.CLS_NDDT, A.CTMNO
    , CASE WHEN B.IKD_GRPCD IN ('FA','MA') THEN 'FAMA' ELSE B.IKD_GRPCD END AS IKD_GRPCD
    , B.CLMDT
    , SUM(B.WONCR_CV_PYAMT) AS PY_AMT
FROM DATABIZ_FUTVAL_YYMM_PRED T
INNER JOIN DATABIZ_FUTVAL_ALL_CUS_INFO_PRED A ON T.CLS_YYMM = A.CLS_YYMM
LEFT JOIN M_CMP_GN_CVRCL_PY_IBNF_LIST B
    ON A.CTMNO = B.CLMPS_CTMNO
    AND B.CLMDT BETWEEN F_LAST_DAY(F_PREV_MONTH(T.CLS_YYMM,'60')) AND FIRST_DAY(T.CLS_YYMM)
GROUP BY T.CLS_YYMM, T.CLS_NDDT, A.CTMNO
    , CASE WHEN B.IKD_GRPCD IN ('FA','MA') THEN 'FAMA' ELSE B.IKD_GRPCD END, B.CLMDT

UNION ALL  -- 소스 테이블 다름 → 중복 불가

-- 자동차 보험
SELECT CLS_YYMM, CLS_NDDT, CTMNO, IKD_GRPCD, CLMDT
    , SUM(RPBL_PY_IBAMT) + SUM(OPTN_PY_IBAMT) AS PY_AMT
FROM (
    SELECT DISTINCT
        T.CLS_YYMM, T.CLS_NDDT, A.CTMNO, 'CA' AS IKD_GRPCD
        , C.CLMDT, B.RPBL_PY_IBAMT, B.OPTN_PY_IBAMT
    FROM DATABIZ_FUTVAL_YYMM_PRED T
    INNER JOIN DATABIZ_FUTVAL_ALL_CUS_INFO_PRED A ON T.CLS_YYMM = A.CLS_YYMM
    LEFT JOIN M_CMP_CR_CLM_CRST B ON A.CTMNO = B.NRDPS_CTMNO
    INNER JOIN M_CMP_CR_CMP_CLM_CR C
        ON B.RCPDT = C.RCPDT AND B.RCP_NV_SEQNO = C.RCP_NV_SEQNO
        AND C.CLMDT BETWEEN F_LAST_DAY(F_PREV_MONTH(T.CLS_YYMM,'60')) AND FIRST_DAY(T.CLS_YYMM)
) AA
GROUP BY CLS_YYMM, CLS_NDDT, CTMNO, IKD_GRPCD, CLMDT;


/* ============================================================================
   [11] 보장분석 이력
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_GNANL_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_GNANL_PRED AS
SELECT DISTINCT A1.*
    , CASE WHEN B1.CTMNO IS NOT NULL THEN 1 ELSE 0 END AS GNANL_YN
    , B1.GNANL_DT, B1.HOMEAPP_YN, B1.STFNO AS GNANL_STFNO
FROM DATABIZ_FUTVAL_ALL_CUS_INFO_PRED A1
LEFT JOIN (
    SELECT T.CLS_YYMM, A.GNANL_NO, B.SND_SRV_SEQNO, A.GNANL_DT, A.STFNO
        , B.CTMNO, B.SND_SRV_TPCD
        , CASE WHEN A.STFNO IN ('8909504','8914327') THEN 1 ELSE 0 END AS HOMEAPP_YN
    FROM DATABIZ_FUTVAL_YYMM_PRED T
    INNER JOIN SFA_GNANL_BA A ON A.GNANL_DT <= FIRST_DAY(T.CLS_YYMM)
    LEFT JOIN SFA_GNANL_SND_SRV_LOG B ON A.GNANL_NO = B.GNANL_NO
    WHERE A.GNANL_PL_TPCD = '10' AND A.ERS_YN = '0'
) B1 ON A1.CTMNO = B1.CTMNO;


/* ============================================================================
   [12] 피보험자 수 및 미성년 여부
   ※ DISTINCT → GROUP BY
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CR_NRD_INFO_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CR_NRD_INFO_PRED AS
SELECT A.CLS_YYMM, A.CRT_CTMNO
    , COUNT(DISTINCT B.CTMNO) AS NRD_CNT
    , MAX(CASE
        WHEN F_ISDATE(F_BIRTH_DAY_DEC(B.CTM_DSCNO)) = 'T'
         AND TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),
                  TO_DATE(F_BIRTH_DAY_DEC(B.CTM_DSCNO),'YYYYMMDD')) / 12) < 20
        THEN 1 ELSE 0 END) AS KIDS_YN
FROM (SELECT CRT_CTMNO, PLYNO, CLS_YYMM
      FROM DATABIZ_FUTVAL_ALL_CR_TEMP_PRED
      WHERE IKD_GRPCD = 'LA'
      GROUP BY CRT_CTMNO, PLYNO, CLS_YYMM) A
INNER JOIN INS_CR_RELPC B
    ON A.PLYNO = B.PLYNO
    AND B.AP_STRDT  <= F_LAST_DAY(A.CLS_YYMM)
    AND B.AP_NDDT    > F_LAST_DAY(A.CLS_YYMM)
    AND B.RELPC_TPCD IN ('02')
GROUP BY A.CLS_YYMM, A.CRT_CTMNO;


/* ============================================================================
   [13] 상품유형별 기가입 PIVOT
   ※ GD_TYPE은 ALL_CR_TEMP_PRED에서 이미 계산됨 → CASE WHEN 제거
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CR_GD_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CR_GD_PRED AS
SELECT *
FROM (
    SELECT CLS_YYMM, CRT_CTMNO, GD_TYPE
        , COUNT(DISTINCT PLYNO) AS PLY_CNT
    FROM DATABIZ_FUTVAL_ALL_CR_TEMP_PRED
    GROUP BY CLS_YYMM, CRT_CTMNO, GD_TYPE
)
PIVOT (MAX(PLY_CNT) FOR GD_TYPE IN (
    'L01' AS L01,'L03' AS L03,'L04' AS L04,'L06' AS L06,'L08' AS L08,
    'SAFE' AS SAFE,'SS' AS SS,'유병자' AS 유병자,'L11' AS L11,'L123' AS L123
)) P;


/* ============================================================================
   [14] 동일 주소 직원 (가까운 이웃 FP)
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_STF_ADD_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_STF_ADD_PRED AS
SELECT DISTINCT A.CTMNO, B.STFNO
FROM (
    SELECT A.*, B.CTM_DSCNO
    FROM CUS_CTM_ADR_CRR A
    LEFT JOIN CUS_CTM B ON A.CTMNO = B.CTMNO
    WHERE AP_ND_DTHMS  >= SYSDATE AND AP_STR_DTHMS < SYSDATE AND ADR_FLGCD = '100'
) A
LEFT JOIN (
    SELECT A.*, B.RSNO
    FROM SAM_STF_ADDR A
    LEFT JOIN SAM_STF B ON A.STFNO = B.STFNO
    WHERE VALD_NDDT >= SYSDATE AND VALD_STRDT < SYSDATE AND ADR_FLGCD = '100'
) B ON A.CTM_DSCNO != B.RSNO
    AND A.DTADR = B.DTADR
    AND A.SD||' '||A.SGNG = B.SD||' '||B.SGNG
    AND NVL(A.RI_OR_LRDLP,'X') = NVL(B.RI_OR_LRDLP,'X')
    AND NVL(A.TWMD,'X') = NVL(B.TWMD,'X')
    AND A.PSTNO = B.PSTNO
WHERE B.STFNO IS NOT NULL;


/* ============================================================================
   [15] 담당 FP 가족계약 여부
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_STF_CR_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_STF_CR_PRED AS
SELECT A.*
    , CASE WHEN B.RELPC_RELCD IN ('02','03','04','05','06','07','08','09','10','14','15','16','36','40')
           THEN 'Y' ELSE 'N' END AS 가족계약여부
    , B.DTCNM AS 관계
FROM (
    SELECT DISTINCT B.CLS_YYMM, A.PLYNO, B.RSNO, B.STFNO, A.CTMNO
    FROM INS_CR_RELPC A
    INNER JOIN (
        SELECT B.CLS_YYMM, STFNO, RSNO
        FROM DATABIZ_FUTVAL_YYMM_PRED T
        INNER JOIN M_ORG_MTHY_BZ_ORGN B ON T.CLS_YYMM = B.CLS_YYMM
        WHERE STF_BZ_STCD = '01'
    ) B ON A.RELPC_TPCD IN ('01','02')
        AND A.CTM_DSCNO = B.RSNO
        AND A.NDS_AP_ND_DTHMS   > F_LAST_DAY(B.CLS_YYMM)
        AND A.NDS_AP_STR_DTHMS <= F_LAST_DAY(B.CLS_YYMM)
        AND A.IKD_GRPCD = 'LA'
) A
LEFT JOIN (
    SELECT A.*, B.DTCNM
    FROM INS_CR_RELPC_REL A
    LEFT JOIN RELCD B ON A.RELPC_RELCD = B.RELCD
) B ON A.PLYNO = B.PLYNO
    AND B.CNFT_RELPC_TPCD = '01' AND B.ST_RELPC_TPCD = '02'
    AND B.NDS_AP_ND_DTHMS   > F_LAST_DAY(A.CLS_YYMM)
    AND B.NDS_AP_STR_DTHMS <= F_LAST_DAY(A.CLS_YYMM);


/* ============================================================================
   [16] 설계청약동의 이력
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_CUSACT_ISPL_AGRE_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_CUSACT_ISPL_AGRE_PRED AS
SELECT DISTINCT
    A1.CLS_YYMM, A1.AGRE_ADMNO, A1.DH_STFNO, C1.CTMNO
    , A1.AGRE_STRDT, A1.AGRE_NDDT
    , CASE WHEN A1.CNT >= 4
            AND A1.AGRE_STRDT <= F_LAST_DAY(A1.CLS_YYMM)
            AND A1.AGRE_NDDT   > F_LAST_DAY(A1.CLS_YYMM)
           THEN 1 ELSE 0 END AS ISPL_AGRE_YN
FROM (
    SELECT T.CLS_YYMM, AGRE_ADMNO, DH_STFNO, CTM_DSCNO
        , MAX(AGRE_STRDT) AS AGRE_STRDT
        , MAX(AGRE_NDDT)  AS AGRE_NDDT
        , COUNT(1)        AS CNT
    FROM DATABIZ_FUTVAL_YYMM_PRED T
    INNER JOIN INS_CRDIF_INQ_AGR_ADM A
        ON A.AP_STR_DTHMS <= F_LAST_DAY(T.CLS_YYMM)
    WHERE CRDIF_INQ_AGRE_YN = '1'
      AND WRCS_KNDCD IN ('02','03','05','06')
      AND CRDIF_INQ_AGRE_MTDCD IN ('01','02','03','07','13','14','17','18','19')
      AND AP_ND_DTHMS = TO_DATE('99991231','YYYYMMDD')
    GROUP BY T.CLS_YYMM, AGRE_ADMNO, DH_STFNO, CTM_DSCNO
) A1
INNER JOIN INS_CRDIF_INQ_AGR_ADM B1
    ON A1.AGRE_ADMNO = B1.AGRE_ADMNO AND B1.WRCS_KNDCD = '06'
    AND (CASE WHEN B1.CRDIF_INQ_AGRE_MTDCD IN ('01','07','11','12') AND B1.RCGNT_STCD = '01' THEN '1'
              WHEN B1.CRDIF_INQ_AGRE_MTDCD NOT IN ('01','07','11','12') THEN '1'
         END) = '1'
INNER JOIN CUS_CTM C1 ON A1.CTM_DSCNO = C1.CTM_DSCNO
WHERE EXISTS (
    SELECT 1 FROM DATABIZ_FUTVAL_ALL_CUS_INFO_PRED B
    WHERE C1.CTMNO = B.CTMNO AND A1.CLS_YYMM = B.CLS_YYMM
);


/* ============================================================================
   [17] 최종 취합 MAIN
============================================================================ */
DROP TABLE DATABIZ_FUTVAL_MAIN_PRED PURGE;
CREATE TABLE DATABIZ_FUTVAL_MAIN_PRED AS
SELECT DISTINCT
    A.CLS_YYMM, A.CTMNO, A.DH_STFNO, B17.CTM_DSCNO
    , CASE WHEN A.CTM_AGE >= 70 THEN 70 WHEN A.CTM_AGE >= 60 THEN 60
           WHEN A.CTM_AGE >= 50 THEN 50 WHEN A.CTM_AGE >= 40 THEN 40
           WHEN A.CTM_AGE >= 30 THEN 30 WHEN A.CTM_AGE >= 20 THEN 20
           WHEN A.CTM_AGE  < 20 THEN 10 ELSE NULL END AS AGE_SEG
    , A.CTM_SEX, A.CA_YN, A.FAMA_YN
    , NVL(SUBSTR(B1.JBCD,1,1),'N')        AS JBCD
    , NVL(TRUNC(B2.INCOME/1000,0)*1000, 0) AS INCOME
    , CASE WHEN B3.HOME_ADR_CHDT >= 60 THEN '5년이상' WHEN B3.HOME_ADR_CHDT >= 48 THEN '4년이상'
           WHEN B3.HOME_ADR_CHDT >= 36 THEN '3년이상' WHEN B3.HOME_ADR_CHDT >= 24 THEN '2년이상'
           WHEN B3.HOME_ADR_CHDT >= 12 THEN '1년이상' WHEN B3.HOME_ADR_CHDT  < 12 THEN '1년미만'
           ELSE '이력없음' END AS HOME_ADR_CHDT
    , CASE WHEN B3.LATS_CR_CC_AGMDT >= 60 THEN '5년이상' WHEN B3.LATS_CR_CC_AGMDT >= 48 THEN '4년이상'
           WHEN B3.LATS_CR_CC_AGMDT >= 36 THEN '3년이상' WHEN B3.LATS_CR_CC_AGMDT >= 24 THEN '2년이상'
           WHEN B3.LATS_CR_CC_AGMDT >= 12 THEN '1년이상' WHEN B3.LATS_CR_CC_AGMDT  < 12 THEN '1년미만'
           ELSE '이력없음' END AS LATS_CR_CC_AGMDT
    , CASE WHEN B3.MKTG_THRPS_UTAGR_STRDT >= 60 THEN '5년이상' WHEN B3.MKTG_THRPS_UTAGR_STRDT >= 48 THEN '4년이상'
           WHEN B3.MKTG_THRPS_UTAGR_STRDT >= 36 THEN '3년이상' WHEN B3.MKTG_THRPS_UTAGR_STRDT >= 24 THEN '2년이상'
           WHEN B3.MKTG_THRPS_UTAGR_STRDT >= 12 THEN '1년이상' WHEN B3.MKTG_THRPS_UTAGR_STRDT  < 12 THEN '1년미만'
           ELSE '이력없음' END AS MKTG_THRPS_UTAGR_STRDT
    , CASE WHEN B3.LATS_CRNTC_MAIL_RCVDT >= 60 THEN '5년이상' WHEN B3.LATS_CRNTC_MAIL_RCVDT >= 48 THEN '4년이상'
           WHEN B3.LATS_CRNTC_MAIL_RCVDT >= 36 THEN '3년이상' WHEN B3.LATS_CRNTC_MAIL_RCVDT >= 24 THEN '2년이상'
           WHEN B3.LATS_CRNTC_MAIL_RCVDT >= 12 THEN '1년이상' WHEN B3.LATS_CRNTC_MAIL_RCVDT  < 12 THEN '1년미만'
           ELSE '이력없음' END AS LATS_CRNTC_MAIL_RCVDT
    , NVL(B4.전속,0) 전속, NVL(B4.교차,0) 교차, NVL(B4.GA,0) GA
    , NVL(B4.TM,0) + NVL(B4.CM,0) AS 다이렉트
    , NVL(B4.방카,0)+NVL(B4.기업,0)+NVL(B4.LIFEWITH,0)+NVL(B4.본사기타,0) AS 기타
    , CASE WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B5.MX_INS),0) >= 60 THEN '5년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B5.MX_INS),0) >= 48 THEN '4년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B5.MX_INS),0) >= 36 THEN '3년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B5.MX_INS),0) >= 24 THEN '2년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B5.MX_INS),0) >= 12 THEN '1년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B5.MX_INS),0)  < 12 THEN '1년미만'
           ELSE '이력없음' END AS MX_INS
    , NVL(B5.CCL_CR_CNT,0) CCL_CR_CNT
    , NVL(B6.NRD_CNT,0) NRD_CNT, NVL(B6.KIDS_YN,0) KIDS_YN
    , CASE WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B8.MX_PLDT),0) >= 60 THEN '5년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B8.MX_PLDT),0) >= 48 THEN '4년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B8.MX_PLDT),0) >= 36 THEN '3년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B8.MX_PLDT),0) >= 24 THEN '2년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B8.MX_PLDT),0) >= 12 THEN '1년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B8.MX_PLDT),0)  < 12 THEN '1년미만'
           ELSE '이력없음' END AS MX_PLDT
    , CASE WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B9.MX_CLMDT),0) >= 60 THEN '5년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B9.MX_CLMDT),0) >= 48 THEN '4년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B9.MX_CLMDT),0) >= 36 THEN '3년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B9.MX_CLMDT),0) >= 24 THEN '2년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B9.MX_CLMDT),0) >= 12 THEN '1년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B9.MX_CLMDT),0)  < 12 THEN '1년미만'
           ELSE '이력없음' END AS MX_CLMDT
    , CASE WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B10.MX_GNANL),0) >= 60 THEN '5년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B10.MX_GNANL),0) >= 48 THEN '4년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B10.MX_GNANL),0) >= 36 THEN '3년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B10.MX_GNANL),0) >= 24 THEN '2년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B10.MX_GNANL),0) >= 12 THEN '1년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B10.MX_GNANL),0)  < 12 THEN '1년미만'
           ELSE '이력없음' END AS MX_GNANL
    , CASE WHEN B11.CTMNO IS NOT NULL THEN 1 ELSE 0 END AS SAME_ADD_YN
    , CASE WHEN B12.CTMNO IS NOT NULL THEN 1 ELSE 0 END AS FMY_CR_YN
    , CASE WHEN B13.CTMNO IS NOT NULL THEN 1 ELSE 0 END AS OTHER_CHNL_YN
    , CASE WHEN B15.PSS_CTM_CVDT IS NOT NULL THEN 1 ELSE 0 END AS PSS_CTM_YN
    , CASE WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),
                CASE WHEN TO_CHAR(B15.INP_DTHMS,'YYYY')='0001' THEN B15.MDF_DTHMS ELSE B15.INP_DTHMS END),0) >= 60 THEN '5년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),
                CASE WHEN TO_CHAR(B15.INP_DTHMS,'YYYY')='0001' THEN B15.MDF_DTHMS ELSE B15.INP_DTHMS END),0) >= 48 THEN '4년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),
                CASE WHEN TO_CHAR(B15.INP_DTHMS,'YYYY')='0001' THEN B15.MDF_DTHMS ELSE B15.INP_DTHMS END),0) >= 36 THEN '3년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),
                CASE WHEN TO_CHAR(B15.INP_DTHMS,'YYYY')='0001' THEN B15.MDF_DTHMS ELSE B15.INP_DTHMS END),0) >= 24 THEN '2년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),
                CASE WHEN TO_CHAR(B15.INP_DTHMS,'YYYY')='0001' THEN B15.MDF_DTHMS ELSE B15.INP_DTHMS END),0) >= 12 THEN '1년이상'
           WHEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),
                CASE WHEN TO_CHAR(B15.INP_DTHMS,'YYYY')='0001' THEN B15.MDF_DTHMS ELSE B15.INP_DTHMS END),0)  < 12 THEN '1년미만'
           ELSE '이력없음' END AS CUS_INP_DT
    , CASE WHEN B16.ISPL_AGRE_YN = 1 THEN '동의'
           WHEN B16.ISPL_AGRE_YN = 0 AND TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B16.AGRE_NDDT),0) >= 60 THEN '5년이상'
           WHEN B16.ISPL_AGRE_YN = 0 AND TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B16.AGRE_NDDT),0) >= 48 THEN '4년이상'
           WHEN B16.ISPL_AGRE_YN = 0 AND TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B16.AGRE_NDDT),0) >= 36 THEN '3년이상'
           WHEN B16.ISPL_AGRE_YN = 0 AND TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B16.AGRE_NDDT),0) >= 24 THEN '2년이상'
           WHEN B16.ISPL_AGRE_YN = 0 AND TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B16.AGRE_NDDT),0) >= 12 THEN '1년이상'
           WHEN B16.ISPL_AGRE_YN = 0 AND TRUNC(MONTHS_BETWEEN(F_LAST_DAY(A.CLS_YYMM),B16.AGRE_NDDT),0)  < 12 THEN '1년미만'
           ELSE '동의이력없음' END AS ISPL_AGRE
    , NVL(B14.PRM,0) PRM
    , NVL(B7.L01,0) L01, NVL(B7.L03,0) L03, NVL(B7.L04,0) L04
    , NVL(B7.L06,0) L06, NVL(B7.L08,0) L08, NVL(B7.SAFE,0) SAFE
    , NVL(B7.SS,0) SS,   NVL(B7.유병자,0) 유병자, NVL(B7.L11,0) L11, NVL(B7.L123,0) L123
FROM (SELECT * FROM DATABIZ_FUTVAL_ALL_CUS_INFO_PRED WHERE LA_YN > 0 AND RELPC_TPCD = '01') A
LEFT JOIN DATABIZ_FUTVAL_CUS_JOB_PRED        B1  ON A.CTMNO=B1.CTMNO AND A.CLS_YYMM=B1.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_CUS_ADD_INCOME_PRED B2  ON A.CTMNO=B2.CTMNO AND A.CLS_YYMM=B2.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_CUS_INFO_PRED       B3  ON A.CTMNO=B3.CTMNO AND A.CLS_YYMM=B3.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_CR_CHNL_PRED        B4  ON A.CTMNO=B4.CTMNO AND A.CLS_YYMM=B4.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_CR_CRR_PRED         B5  ON A.CTMNO=B5.CTMNO AND A.DH_STFNO=B5.DH_STFNO AND A.CLS_YYMM=B5.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_CR_NRD_INFO_PRED    B6  ON A.CTMNO=B6.CRT_CTMNO AND A.CLS_YYMM=B6.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_CR_GD_PRED          B7  ON A.CTMNO=B7.CRT_CTMNO AND A.CLS_YYMM=B7.CLS_YYMM
LEFT JOIN (SELECT CLS_YYMM, CTMNO, CE_STFNO, MAX(PLDT) AS MX_PLDT
           FROM DATABIZ_FUTVAL_PL_PRED GROUP BY CLS_YYMM, CTMNO, CE_STFNO) B8
    ON A.CTMNO=B8.CTMNO AND A.CLS_YYMM=B8.CLS_YYMM AND A.DH_STFNO=B8.CE_STFNO
LEFT JOIN (SELECT CLS_YYMM, CTMNO, MAX(CLMDT) AS MX_CLMDT
           FROM DATABIZ_FUTVAL_CLM_PRED GROUP BY CLS_YYMM, CTMNO) B9
    ON A.CTMNO=B9.CTMNO AND A.CLS_YYMM=B9.CLS_YYMM
LEFT JOIN (SELECT CLS_YYMM, CTMNO, GNANL_STFNO, MAX(GNANL_DT) AS MX_GNANL
           FROM DATABIZ_FUTVAL_GNANL_PRED GROUP BY CLS_YYMM, CTMNO, GNANL_STFNO) B10
    ON A.CTMNO=B10.CTMNO AND A.CLS_YYMM=B10.CLS_YYMM AND A.DH_STFNO=B10.GNANL_STFNO
LEFT JOIN DATABIZ_FUTVAL_STF_ADD_PRED        B11 ON A.CTMNO=B11.CTMNO AND A.DH_STFNO=B11.STFNO
LEFT JOIN DATABIZ_FUTVAL_STF_CR_PRED         B12 ON A.CTMNO=B12.CTMNO AND A.DH_STFNO=B12.STFNO AND A.CLS_YYMM=B12.CLS_YYMM
LEFT JOIN (
    SELECT *
    FROM (
        SELECT CLS_YYMM, CTMNO
            , CASE WHEN NVL(전속,0) > 0 THEN 1 ELSE 0 END AS 전속
            , CASE WHEN NVL(교차,0) > 0 THEN 1 ELSE 0 END AS 교차
            , CASE WHEN NVL(GA,0)   > 0 THEN 1 ELSE 0 END AS GA
            , CASE WHEN NVL(TM,0)+NVL(CM,0) > 0 THEN 1 ELSE 0 END AS 다이렉트
            , CASE WHEN NVL(방카,0)+NVL(기업,0)+NVL(LIFEWITH,0)+NVL(본사기타,0) > 0 THEN 1 ELSE 0 END AS 기타
        FROM DATABIZ_FUTVAL_CR_CHNL_PRED
    )
    WHERE 전속+교차+GA+다이렉트+기타 > 1
) B13 ON A.CTMNO=B13.CTMNO AND A.CLS_YYMM=B13.CLS_YYMM
LEFT JOIN (
    SELECT CLS_YYMM, CRT_CTMNO, DH_STFNO, SUM(LTRM_MPY_CV_PRM) AS PRM
    FROM DATABIZ_FUTVAL_ALL_CR_TEMP_PRED WHERE IKD_GRPCD = 'LA'
    GROUP BY CLS_YYMM, CRT_CTMNO, DH_STFNO
) B14 ON A.CTMNO=B14.CRT_CTMNO AND A.DH_STFNO=B14.DH_STFNO AND A.CLS_YYMM=B14.CLS_YYMM
LEFT JOIN CUS_BZ_FML_CTM B15 ON A.CTMNO=B15.CTMNO AND A.DH_STFNO=B15.STFNO
LEFT JOIN (
    SELECT A.*, ROW_NUMBER() OVER (PARTITION BY CLS_YYMM, CTMNO ORDER BY AGRE_NDDT DESC) AS RN
    FROM DATABIZ_FUTVAL_CUSACT_ISPL_AGRE_PRED A
) B16 ON A.CTMNO=B16.CTMNO AND A.CLS_YYMM=B16.CLS_YYMM AND B16.RN=1
LEFT JOIN CUS_CTM B17 ON A.CTMNO = B17.CTMNO;


/* ============================================================================
   [18] 전체 계약 (CRM 마트용) — CHNL_MAP 재사용 (당월 org 기준)
   ※ 원본 CHNL CASE WHEN 55줄 → STF_CHNL_MAP JOIN 1줄
============================================================================ */
DROP TABLE CRM_MART_ALL_CR_TEMP PURGE;
CREATE TABLE CRM_MART_ALL_CR_TEMP AS
SELECT A.*, B.CHNL
FROM DATABIZ_FUTVAL_YYMM_PRED T
LEFT JOIN M_CRM_MTHY_PS_CR A ON A.CLS_YYMM = T.CLS_YYMM
LEFT JOIN DATABIZ_FUTVAL_STF_CHNL_MAP B
    ON T.CLS_YYMM = B.CLS_YYMM AND A.DH_STFNO = B.STFNO;


/* ============================================================================
   [19] 고객 기본정보 (CRM 마트용)
   ※ F_BIRTH_DAY_DEC/F_SEX_DEC 서브쿼리 1회 호출
============================================================================ */
DROP TABLE CRM_MART_ALL_CUS_INFO PURGE;
CREATE TABLE CRM_MART_ALL_CUS_INFO AS
SELECT
    CLS_YYMM, CTMNO, RELPC_TPCD
    , CASE WHEN F_ISDATE(BRTH) = 'T'
           THEN TRUNC(MONTHS_BETWEEN(F_LAST_DAY(CLS_YYMM), TO_DATE(BRTH,'YYYYMMDD')) / 12)
      END AS CTM_AGE
    , CASE WHEN SEX = 'M' THEN '1.M' WHEN SEX = 'F' THEN '2.F' END AS CTM_SEX
    , MAX(CASE WHEN IKD_GRPCD = 'LA'         THEN 1 ELSE 0 END) AS LA_YN
    , MAX(CASE WHEN IKD_GRPCD = 'CA'         THEN 1 ELSE 0 END) AS CA_YN
    , MAX(CASE WHEN IKD_GRPCD IN ('FA','MA') THEN 1 ELSE 0 END) AS FAMA_YN
FROM (
    SELECT A.CLS_YYMM, C.CTMNO, C.RELPC_TPCD, C.IKD_GRPCD,
           F_BIRTH_DAY_DEC(C.CTM_DSCNO) AS BRTH,
           F_SEX_DEC(C.CTM_DSCNO)       AS SEX
    FROM CRM_MART_ALL_CR_TEMP A
    INNER JOIN DATABIZ_FUTVAL_YYMM_PRED T ON A.CLS_YYMM = T.CLS_YYMM
    INNER JOIN INS_CR_RELPC C
        ON A.PLYNO = C.PLYNO
        AND C.NDS_AP_STR_DTHMS <= T.CLS_NDDT AND C.NDS_AP_ND_DTHMS > T.CLS_NDDT
        AND C.RELPC_TPCD IN ('01','02')
        AND C.RELPC_STCD IN ('01','04')
)
GROUP BY CLS_YYMM, CTMNO, RELPC_TPCD, BRTH, SEX;


/* ============================================================================
   [20] 보험료 (월납환산/적립/보장)
   ※ GD_TYPE: CRM_MART_ALL_CR_TEMP.GD_TYPE 직접 참조 (CASE WHEN 제거)
============================================================================ */
DROP TABLE CRM_MART_LA_PRM PURGE;
CREATE TABLE CRM_MART_LA_PRM AS
SELECT
    A.CLS_YYMM, A.PLYNO, A.CRT_CTMNO
    , A.GD_TYPE
    , A.LTRM_MPY_CV_PRM
    , B.CU_PRM, B.GN_PRM
FROM DATABIZ_FUTVAL_YYMM_PRED T
INNER JOIN SDADAM.CRM_MART_ALL_CR_TEMP A ON A.CLS_YYMM = T.CLS_YYMM
LEFT JOIN M_ERL_LTRM_CR_MTT B
    ON A.PLYNO = B.PLYNO
    AND B.AP_STRDT <= F_LAST_DAY(A.CLS_YYMM)
    AND B.AP_NDDT   > F_LAST_DAY(A.CLS_YYMM);


/* ============================================================================
   [21] 세그먼트 마케팅 현재가치
============================================================================ */
DROP TABLE SEG_MkTG_PRES_VAL PURGE;
CREATE TABLE SEG_MKTG_PRES_VAL AS
SELECT DISTINCT
    A.CLS_YYMM, A.CTMNO, A.CTM_AGE, B.PLY_CNT, D.SM_LTRM_PRM
    , CASE WHEN A.CTM_AGE >= 70 THEN 70 WHEN A.CTM_AGE >= 60 THEN 60
           WHEN A.CTM_AGE >= 50 THEN 50 WHEN A.CTM_AGE >= 40 THEN 40
           WHEN A.CTM_AGE >= 30 THEN 30 WHEN A.CTM_AGE >= 20 THEN 20
           WHEN A.CTM_AGE  < 20 THEN 10 ELSE NULL END AS CTM_AGE_SEG
FROM (
    SELECT A.*
    FROM DATABIZ_FUTVAL_YYMM_PRED T
    INNER JOIN SDADAM.CRM_MART_ALL_CUS_INFO A ON A.CLS_YYMM = T.CLS_YYMM
    WHERE RELPC_TPCD = '02' AND LA_YN = 1
) A
LEFT JOIN (
    SELECT A.CLS_YYMM, C.CTMNO, COUNT(DISTINCT A.PLYNO) AS PLY_CNT
    FROM DATABIZ_FUTVAL_YYMM_PRED T
    INNER JOIN SDADAM.CRM_MART_ALL_CR_TEMP A ON A.CLS_YYMM = T.CLS_YYMM
    INNER JOIN INS_CR_RELPC C
        ON A.PLYNO = C.PLYNO
        AND C.NDS_AP_STR_DTHMS <= F_LAST_DAY(A.CLS_YYMM) AND C.NDS_AP_ND_DTHMS > F_LAST_DAY(A.CLS_YYMM)
        AND C.RELPC_TPCD IN ('02') AND C.RELPC_STCD IN ('01','04')
    WHERE A.IKD_GRPCD = 'LA'
      AND A.MKTG_GD_CSFCD NOT IN ('L12','L13')
      AND A.GDNM NOT LIKE '%실손의료보험%'
    GROUP BY A.CLS_YYMM, C.CTMNO
) B ON A.CTMNO=B.CTMNO AND A.CLS_YYMM=B.CLS_YYMM
LEFT JOIN (
    SELECT A.CLS_YYMM, C.CTMNO, SUM(A.LTRM_MPY_CV_PRM) AS SM_LTRM_PRM
    FROM DATABIZ_FUTVAL_YYMM_PRED T
    INNER JOIN CRM_MART_LA_PRM A ON A.CLS_YYMM = T.CLS_YYMM
    INNER JOIN INS_CR_RELPC C
        ON A.PLYNO = C.PLYNO
        AND C.NDS_AP_STR_DTHMS <= F_LAST_DAY(A.CLS_YYMM) AND C.NDS_AP_ND_DTHMS > F_LAST_DAY(A.CLS_YYMM)
        AND C.RELPC_TPCD IN ('02') AND C.RELPC_STCD IN ('01','04')
    WHERE A.GD_TYPE NOT IN ('SS','L123')
    GROUP BY A.CLS_YYMM, C.CTMNO
) D ON A.CTMNO=D.CTMNO AND A.CLS_YYMM=D.CLS_YYMM
WHERE A.CTMNO NOT IN (
    SELECT A.CTMNO FROM CUS_CTM A
    INNER JOIN M_ORG_MTHY_BZ_ORGN B
        ON B.CLS_YYMM IN (SELECT CLS_YYMM FROM DATABIZ_FUTVAL_YYMM_PRED)
        AND B.RETDT >= SYSDATE AND B.STF_BZ_STCD = '01'
        AND A.CTM_DSCNO = B.RSNO
);


/* ============================================================================
   [22] 담보 정보 (WIDE → LONG)
   ※ 17개 UNION ALL → UNPIVOT 1개 (동일 소스 17회 스캔 → 1회)
============================================================================ */
DROP TABLE SEG_MKTG_PRES_CVR_INFO PURGE;
CREATE TABLE SEG_MKTG_PRES_CVR_INFO AS
SELECT A.CLS_YYMM, A.CTMNO, U.담보명, U.담보가입금액
FROM DATABIZ_FUTVAL_YYMM_PRED T
INNER JOIN SDADAM.M_BIZ_CTM_INFO_CVR_LIST A ON A.CLS_YYMM = T.CLS_YYMM
UNPIVOT INCLUDE NULLS (
    담보가입금액 FOR 담보명 IN (
        DSDE_AMT                  AS '질병사망',
        DSAS_SLOBS_AMT            AS '질병후유장해',
        DSAS_DGR_SLOBS_AMT        AS '질병고도후유장해',
        SMLY_CANCR_DASCS_AMT      AS '유사암진단비',
        CANCR_DASCS_AMT           AS '암진단비',
        HAMT_CANCR_DASCS_AMT      AS '고액암진단비',
        CRLR_DSAS_DASCS_AMT       AS '뇌혈관질환진단비',
        ISMC_HEART_DSAS_DASCS_AMT AS '허혈성심장질환진단비',
        AMIFN_INCR_DASCS_AMT      AS '급성신근경색증진단비',
        FOCUS_ANTI_MEDI_APPR_MDCF AS '표적항암약물허가치료비',
        CANCR_OPCCS_AMT           AS '암수술비',
        CRLR_DSAS_OPCCS_AMT       AS '뇌혈관질환수술비',
        ISMC_HEART_DSAS_OPCCS_AMT AS '허혈성심장질환수술비',
        DSAS_OPCCS_AMT            AS '질병수술비',
        INJR_OPCCS_AMT            AS '상해수술비',
        GB_AMT                    AS '간병인사용상해',
        GB_AMT2                   AS '간병인사용질병'
    )
) U;
